config/routes.rb
Listest::Application.routes.draw do
  resources :users
  root "time_clocks#index"
  get "time_clocks/index"
  post "time_clocks/create"
  get "time_clocks/status"
  post "time_clocks/report"

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :work_times

  def clock_in
    self.update_attributes(status: "CLOCKED IN")
    WorkTime.create(user_id: self.id, clocked_in_at: Time.now)
  end

  def clock_out
    self.update_attributes(status: "CLOCKED OUT")
    self.work_times.last.update_attributes(clocked_out_at: Time.now)
  end

  def time_worked_past_week
    self.work_times.where("clocked_in_at >= '#{7.days.ago}'")
  end

end

app/models/work_time.rb
class WorkTime < ActiveRecord::Base
  belongs_to :user

  def set_locked_out_at(id)
    WorkTime.find_by(user_id: id).last.update_attributes(clocked_out_at: Time.now)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/time_clocks_controller.rb
class TimeClocksController < ApplicationController
  def index
  end

  def create
    @user = User.find_by(employee_id: params[:employee_id])
    if @user
      if @user.status.try(:upcase) == "CLOCKED IN"
        @user.clock_out
      else
        @user.clock_in
      end
      redirect_to :action => "status", :id => @user
    else
      redirect_to root_path
    end
  end

  def status
    @user = User.find(params[:id])
    @users = User.all
  end

  def report
    @user = User.find(params[:user_id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path
    else
      render :new
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :employee_id, :role)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def time_diff(clocked_out, clocked_in)
    diff = clocked_out - clocked_in
    Time.at(diff.to_i.abs).utc.strftime "%H:%M:%S"
  end
end

app/helpers/time_clocks_helper.rb
module TimeClocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">

      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>

      <!-- Be sure to leave the brand out there if you want it shown -->
      <a class="brand" href="#" id="logo">Time & Attendance Test App</a>

      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
        <!-- .nav, .navbar-search, .navbar-form, etc -->
        <ul class="nav pull-right">
          <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "Time Clock", root_path %></li>
          <li class="<%= 'active' if current_page?(users_path) %>"><%= link_to "Manage Users", users_path %></li>
        </ul>
      </div>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Listest</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>
  <div class="container" %>
    <%= yield %>
  </div>

</body>
</html>

app/views/time_clocks/_report.html.erb
<%= user.employee_id %> (<%= user.first_name %> <%= user.last_name %>) <br />
<% user.time_worked_past_week.each do |time| %>
  Clocked In: <%= time.clocked_in_at %> |
  Clocked Out: <%= time.clocked_out_at %> |
  Total Time Worked: <%= time_diff(time.clocked_out_at, time.clocked_in_at) if time.clocked_out_at%><br />
<% end %>

app/views/time_clocks/index.html.erb
<h1>Time Clock</h1>

<%= form_tag time_clocks_create_path do %>
  <div class="field">
    <%= label_tag :employee_id, "Employee ID" %> <%= text_field_tag :employee_id %>
  </div>
  <div class="actions">
    <%= submit_tag "Clock In/Out" %>
  </div>
<% end %>

app/views/time_clocks/report.html.erb
<h1> My Report </h1>
<%= render :partial => 'report', :locals => { :user => @user } %>

app/views/time_clocks/status.html.erb
<h1>Time Status</h1>

<p>You are <%= @user.status.downcase %>!</p>

<% if @user.status.try(:upcase) == "CLOCKED IN" %>
  Clocked In: <%= @user.work_times.last.clocked_in_at %>
<% elsif @user.status.try(:upcase) == "CLOCKED OUT" %>
  Clocked In: <%= @user.work_times.last.clocked_in_at %> |
  Clocked Out: <%= @user.work_times.last.clocked_out_at %> |
  Total Time Worked: <%= time_diff(@user.work_times.last.clocked_out_at, @user.work_times.last.clocked_in_at) %> <br /><br />
<% end %>

<%= button_to "My Weekly Report", time_clocks_report_path(:user_id => @user.id) %> <br />

<% if @user.role.try(:upcase) == "ADMINISTRATOR" && @user.status.try(:upcase) == "CLOCKED IN" %>
  <b>Users Report</b><br /><br />
  <% @users.each do |user| %>
    <%= render :partial => 'report', :locals => { :user => user } %>
    <br />
  <% end %>
<% end %>

app/views/users/index.html.erb
<h1>Users</h1>

<h2><%= link_to "Add User", new_user_path %></h2> <br />

<% unless @users.blank? %>
  <% @users.each do |user| %>
    <li><%= user.employee_id %> (<%= user.first_name %> <%= user.last_name %>)
            <%= link_to "Delete", user, :method => :delete %>
    </li>
  <% end %>
<% end %>

app/views/users/new.html.erb
<h1> Add Users</h1>
<%= form_for @user do |f| %>
  <div class="fields">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %><br />
    <%= f.label :last_name %>
    <%= f.text_field :last_name %><br />
    <%= f.label :employee_id, "Employee ID" %>
    <%= f.text_field :employee_id %><br />
    <%= f.label :role %>
    <%= f.select :role, options_for_select(['EMPLOYEE', 'ADMINISTRATOR']) %><br />
  </div>
  <div class="actions">
    <%= f.submit "Add User" %>
  </div>
<% end %>